Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da


#Conclave

Atras=Atzera

# Botones de MainGUI
MainGUI.OpenConclave=Konklabea ireki
MainGUI.ManageVoting=Bozketa kudeatu
MainGUI.CastVote=Botoa eman

# Textos de OpenConclaveGUI
OpenConclaveGUI.Title=Izendapen zerrenda
OpenConclaveGUI.ButtonOpen=Konklabea ireki
OpenConclaveGUI.ElectorsCount=80 urtetik beherako hautesleak:

# Textos de VoteGUI
VoteGUI.Title=Bozkatu
VoteGUI.Elector=Hauteslea:
VoteGUI.Candidate=Hautagaia:
VoteGUI.Vote=Botoa eman

#Textos de ManageVotingGUI
ManageVotingGUI.Title=Bozketa kudeatu
ManageVotingGUI.Open=Bozketa ireki
ManageVotingGUI.Close=Bozketa itxi
ManageVotingGUI.Update=Eguneratu
ManageVotingGUI.NumVoting=Uneko bozketa
ManageVotingGUI.VoteCount=Boto zenbaketa

# Mensajes de error de las excepciones
Exceptions.ConclaveAlreadyOpen=Badago jada irekitako konklabe bat
Exceptions.VotingNotFinished=Ez da ordubete igaro hasieratik
Exceptions.AlreadyVoted=Kardinal honek dagoeneko bozkatu du
Exceptions.NoActiveVoting=Ez dago bozketa aktiborik